name: My First CI

on:
  push:
    branches:
      - main

jobs:
  explore-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Print current directory (before checkout)
        run: pwd

      - name: List files (before checkout)
        run: ls -la

      - name: Checkout repository
        run: actions/checkout@v4
        
      - name: Print current directory (after checkout)
        run: pwd

      - name: List files (after checkout)
        run: ls -la

      - name: Show package.json
        run: cat package.json